// Code generated by hertz generator.

package demoapi

import (
	"context"

	demoapi "easy-note/temp/demoapi/biz/model/demoapi"
	"github.com/cloudwego/hertz/pkg/app"
)

// CreateUser .
// @router /v2/user/register [POST]
func CreateUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req demoapi.CreateUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(demoapi.CreateUserResponse)

	c.JSON(200, resp)
}
