// Code generated by hertz generator.

package demoapi

import (
	"context"
	"easy-note/cmd/api/biz/model/demoapi"
	"easy-note/cmd/api/biz/rpc"
	"easy-note/kitex_gen/demonote"
	"easy-note/pkg/consts"
	"easy-note/pkg/errno"
	"github.com/cloudwego/hertz/pkg/app"
)

// CreateNote .
// @router /v2/note [POST]
func CreateNote(ctx context.Context, c *app.RequestContext) {
	var err error
	var req demoapi.CreateNoteRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		SendResponse(c, errno.ConvertErr(err), nil)
		return
	}
	v, _ := c.Get(consts.IdentityKey)
	err = rpc.CreateNote(context.Background(), &demonote.CreateNoteRequest{
		Title:   req.Title,
		Content: req.Content,
		UserId:  v.(*demoapi.User).UserID,
	})
	if err != nil {
		SendResponse(c, errno.ConvertErr(err), nil)
		return
	}
	SendResponse(c, errno.Success, nil)
}

// QueryNote .
// @router /v2/note/query [GET]
func QueryNote(ctx context.Context, c *app.RequestContext) {
	var err error
	var req demoapi.QueryNoteRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		SendResponse(c, errno.ConvertErr(err), nil)
		return
	}
	v, _ := c.Get(consts.IdentityKey)
	notes, total, err := rpc.QueryNotes(context.Background(), &demonote.QueryNoteRequest{
		UserId:    v.(*demoapi.User).UserID,
		SearchKey: req.SearchKey,
		Offset:    req.Offset,
		Limit:     req.Limit,
	})
	if err != nil {
		SendResponse(c, errno.ConvertErr(err), nil)
		return
	}
	SendResponse(c, errno.Success, map[string]interface{}{
		consts.Total: total,
		consts.Notes: notes,
	})
}

// UpdateNote .
// @router /v2/note/:note_id [PUT]
func UpdateNote(ctx context.Context, c *app.RequestContext) {
	var err error
	var req demoapi.UpdateNoteRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		SendResponse(c, errno.ConvertErr(err), nil)
		return
	}
	v, _ := c.Get(consts.IdentityKey)
	err = rpc.UpdateNote(context.Background(), &demonote.UpdateNoteRequest{
		NoteId:  req.NoteID,
		UserId:  v.(*demoapi.User).UserID,
		Title:   req.Title,
		Content: req.Content,
	})
	if err != nil {
		SendResponse(c, errno.ConvertErr(err), nil)
		return
	}
	SendResponse(c, errno.Success, nil)
}

// DeleteNote .
// @router /v2/note/:note_id [DELETE]
func DeleteNote(ctx context.Context, c *app.RequestContext) {
	var err error
	var req demoapi.DeleteNoteRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		SendResponse(c, errno.ConvertErr(err), nil)
		return
	}
	v, _ := c.Get(consts.IdentityKey)
	err = rpc.DeleteNote(context.Background(), &demonote.DeleteNoteRequest{
		NoteId: req.NoteID,
		UserId: v.(*demoapi.User).UserID,
	})
	if err != nil {
		SendResponse(c, errno.ConvertErr(err), nil)
		return
	}
	SendResponse(c, errno.Success, nil)
}
