// Code generated by hertz generator.

package demoapi

import (
	"context"
	"easy-note/cmd/api/biz/model/demoapi"
	"easy-note/cmd/api/biz/rpc"
	"easy-note/kitex_gen/demouser"
	"easy-note/pkg/errno"
	"github.com/cloudwego/hertz/pkg/app"
)

// CreateUser .
// @router /v2/user/register [POST]
func CreateUser(_ context.Context, c *app.RequestContext) {
	var err error
	var req demoapi.CreateUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		SendResponse(c, errno.ConvertErr(err), nil)
		return
	}
	err = rpc.CreateUser(context.Background(), &demouser.CreateUserRequest{
		Username: req.Username,
		Password: req.Password,
	})
	if err != nil {
		SendResponse(c, errno.ConvertErr(err), nil)
		return
	}
	SendResponse(c, errno.Success, nil)
}
