// Code generated by hertz generator.

package main

import (
	"easy-note/cmd/api/rpc"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func Init() {
	rpc.Init()
}

func main() {
	h := server.Default()

	register(h)

	h.Spin()
}
