// Code generated by hertz generator.

package main

import (
	"context"
	"easy-note/cmd/api/biz/handler"
	"easy-note/cmd/api/biz/handler/demoapi"
	"easy-note/pkg/errno"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
	r.NoRoute(func(ctx context.Context, c *app.RequestContext) { // used for HTTP 404
		demoapi.SendResponse(c, errno.ServiceErr, nil)
	})
	r.NoMethod(func(ctx context.Context, c *app.RequestContext) { // used for HTTP 405
		demoapi.SendResponse(c, errno.ServiceErr, nil)
	})
}
