// Code generated by hertz generator.

package handler

import (
	"context"
	"easy-note/cmd/api/model"
	"github.com/cloudwego/hertz/pkg/app"
)

// CreateUser .
// @router /v2/user/register [POST]
func CreateUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req model.CreateUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(model.CreateUserResponse)

	c.JSON(200, resp)
}
